## Set the API endpoint used to create the Namespace resource.
apiVersion: v1
## Define the type of resource.
kind: Namespace
## Set the parameters that make the object identifiable.
metadata:
  name: {{ .Values.namespace.name }}
